name: Deploy

on:
  push:
    branches:
      - main

env:
  DEPLOY_PATH: /home/boss/webapps/data-code-info--server/client
  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
  BUILD_SCRIPT: npm run build
  BUILD_SCRIPT_OUTPUT: dist
  VUE_APP_ADDRESS: https://data-code-info.ru

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info - DEPLOY_SERVER_HOST
        run: echo ${{ secrets.DEPLOY_SERVER_HOST }}
      # test
      - name: Print Info - DEPLOY_SERVER_PORT
        run: echo ${{ secrets.DEPLOY_SERVER_PORT }}
      # test
      - name: Print Info - DEPLOY_SERVER_USERNAME
        run: echo ${{ secrets.DEPLOY_SERVER_USERNAME }}
      # test
      - name: Print Info - DEPLOY_SERVER_KEY
        run: echo ${{ secrets.DEPLOY_SERVER_KEY }}
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: Build Appliction
        run: $BUILD_SCRIPT
      # Доставляем собранное приложение на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}/
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at http://data-code-info.ru/"
